
# version: '3.8'

services:
  web:
  # to select app direacti to build app
    build: .
    # wep server to start djnjo + host &port
    # نستخدم gunicorn كخادم ويب بدلاً من runserver لأنه أكثر قوة لإنتاج البيئة.

    command: gunicorn summayies_app.wsgi:application --bind 0.0.0.0:8000
    # add volume to selct app root
    volumes:
      - .:/app
      # select tho port out of the continear 
      # localhost:8000
    ports:
      - "8000:8000"
      # env vilt to add scret key like apui key and datbase paswored
    env_file:
      - .env
      # this min to work wep db is reqieard 
    depends_on:
      - db

  db:
  # postgres version 15

    image: postgres:15
    # postgres data will save in this volume 
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: adminsummary
      POSTGRES_PASSWORD: Ah0108704401
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  postgres_data:


